v1.1 additions
added clearcache as a function
added aliassrc_refresh

diff --git a/aliasrc b/aliasrc
--- a/aliasrc
+++ b/aliasrc
@@ -192,13 +192,21 @@ function aliasrc_update() {
 	(echo -e "$OLD" > "$backup_name" && echo -e "Backed up current aliasrc to '$backup_name'.") || (printf "WARNING: Backup failed, do you wish to proceed anyways? [y/N] " && askForConsent)
 	if [[ ! $consent == 1 ]]; then return; fi
 	
-	(echo "$NEW" > "$PATH_aliasrc") && (echo "Update complete. (Re)source aliasrc or restart current session to apply new changes.")
+	echo "$NEW" > "$PATH_aliasrc" && echo "Update complete. (Re)source aliasrc or restart current session to apply new changes."
+}
+function aliasrc_clearcache() {
+	rm $PATH_cache/*.alias
 }
 
+# Clear cache before import:
+aliasrc_clearcache
+
 # Add aliasrc commands:
-cmd "aliashelp" aliashelp "Displays help information about added aliases."
-cmd "clearaliascache" "rm $PATH_cache/*.alias && rm $PATH_backup/*.backup*" "Clears cached alias files in '$PATH_cache'."
-cmd "aliasrc_update" aliasrc_update "Updates aliasrc, if new version is available."
+cmd "aliashelp" "aliashelp" "Displays help information about added aliases."
+
+cmd "aliasrc_clearcache" "aliasrc_clearcache" "Clears cached alias files in '$PATH_cache'."
+cmd "aliasrc_update" "aliasrc_update" "Updates aliasrc, if new version is available."
+cmd "aliasrc_refresh" "(source $PATH_aliasrc && echo -e 'Aliasrc refreshed!') || (echo -e 'Aliasrc could not be refreshed...')" "Refreshes your aliases"
 
 # Load user aliases:
 source "$PATH_alias_list"
