v1.1
- update function missing "()" lead to unnecessary, invisible consent question
- added colours to updater
- added support for forking/alternative repositories

diff --git a/aliasrc b/aliasrc
--- a/aliasrc
+++ b/aliasrc
@@ -3,6 +3,9 @@
 DEFAULT_variables='#!/bin/bash
 # This file was automatically generated by your aliasrc file!\n
 
+# Repository Location:
+PATH_repository="https://raw.githubusercontent.com/NiroUwU/aliasrc/main/aliasrc"
+
 # Directory Paths:
 PATH_cache=~/.cache/aliasrc
 PATH_backup="$PATH_cache/backup"
@@ -16,6 +19,7 @@ PATH_alias_list=~/alias_list
 COL_reset="\\e[0m"
 COL_error="\\e[31m"
 COL_warning="\\e[33m"
+COL_update="\\e[33m"
 
 # Aliashelp Title text and Colours:
 TEXT_alias="Alias:        "
@@ -158,22 +162,22 @@ function aliasrc_update() {
 		fi
 	}
 	# Aliasrc source:
-	local repository="NiroUwU/aliasrc/main/aliasrc"
-	local update_url="https://raw.githubusercontent.com/$repository"
-
-	local NEW=$(curl $update_url)        || return
-	local OLD=$(curl file:$PATH_aliasrc) || return
+	local update_url="$PATH_repository"
+	
+	echocoloured "$COL_update" "Fetching Repository '$update_url'\n"
+	local NEW=$(curl $update_url)
+	local OLD=$(curl file:$PATH_aliasrc)
 	
 	# No differences found, return:
 	if [[ "$NEW" == "$OLD" ]]; then
-		echo -e "Your aliasrc is up-to date! Quitting updater. :)"
+		echo -e "\nYour aliasrc is up-to date! Quitting updater. :)"
 		return
 	fi
 
 	# Weird stuff going on with curl, asking user:
 	if [[ ${#NEW} -lt ${#OLD}/3 ]]; then
 		echo -e "\n>>> Start of fetched data:\n\n$COL_error$NEW$COL_reset\n\n>>> End of fetched data\n"
-		printf "WARNING: Fetched possibly corrupted or wrong file! Continue anyways? [y/N] " && askForConsent
+		printcoloured "$COL_error" "WARNING: Fetched possibly corrupted or wrong file! Continue anyways? [y/N] " && askForConsent
 	fi
 	if [[ ! $consent == 1 ]]; then return; fi
 	
@@ -186,10 +190,10 @@ function aliasrc_update() {
 	local backup_time=$(date +%Y-%m-%d_%H:%M:%S)
 	local backup_name="$PATH_backup/aliasrc.backupfrom_$backup_time"
 
-	(echo -e "$OLD" > "$backup_name" && echo -e "Backed up current aliasrc to '$backup_name'.") || printf "WARNING: Backup failed, do you wish to proceed anyways? [y/N] " && askForConsent
+	(echo -e "$OLD" > "$backup_name" && echo -e "Backed up current aliasrc to '$backup_name'.") || (printf "WARNING: Backup failed, do you wish to proceed anyways? [y/N] " && askForConsent)
 	if [[ ! $consent == 1 ]]; then return; fi
 	
-	(echo "$NEW" > $PATH_aliasrc) && (echo "Update complete. (Re)source aliasrc or restart session to apply new changes.")
+	(echo "$NEW" > "$PATH_aliasrc") && (echo "Update complete. (Re)source aliasrc or restart current session to apply new changes.")
 }
 
 # Add aliasrc commands:
